import { ElInput, ElButton, ElButtonGroup, ElOption, ElSelect, ElCollapse, ElCollapseItem, ElMenu, ElMenuItem, ElMenuItemGroup, ElSubMenu, ElIcon, ElSwitch, ElForm, ElRadio, ElRadioButton, ElRadioGroup, ElCheckbox, ElTabs, ElTabPane, ElInputNumber } from 'element-plus'
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component("ElInput", ElInput)
    nuxtApp.vueApp.component("ElButton", ElButton)
    nuxtApp.vueApp.component("ElButtonGroup", ElButtonGroup)
    nuxtApp.vueApp.component("ElSelect", ElSelect)
    nuxtApp.vueApp.component("ElOption", ElOption)
    nuxtApp.vueApp.component("ElCollapse", ElCollapse)
    nuxtApp.vueApp.component("ElCollapseItem", ElCollapseItem)
    nuxtApp.vueApp.component("ElMenu", ElMenu)
    nuxtApp.vueApp.component("ElMenuItem", ElMenuItem)
    nuxtApp.vueApp.component("ElSubMenu", ElSubMenu)
    nuxtApp.vueApp.component("ElIcon", ElIcon)
    nuxtApp.vueApp.component("ElMenuItemGroup", ElMenuItemGroup)
    nuxtApp.vueApp.component("ElSwitch", ElSwitch)
    nuxtApp.vueApp.component("ElForm", ElForm)
    nuxtApp.vueApp.component("ElRadio", ElRadio)
    nuxtApp.vueApp.component("ElRadioButton", ElRadioButton)
    nuxtApp.vueApp.component("ElRadioGroup", ElRadioGroup)
    nuxtApp.vueApp.component("ElCheckbox", ElCheckbox)
    nuxtApp.vueApp.component("ElTabs", ElTabs)
    nuxtApp.vueApp.component("ElTabPane", ElTabPane)
    nuxtApp.vueApp.component("ElInputNumber", ElInputNumber)
})